DROP DATABASE IF EXISTS the_eye_db;
CREATE DATABASE the_eye_db;
USE the_eye_db;


CREATE TABLE employee (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER NOT NULL,
  manager_id INTEGER NOT NULL,
  CONSTRAINT fk_party FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE SET NULL,
  CONSTRAINT fk_party FOREIGN KEY (manager_id) REFERENCES manager(id) ON DELETE SET NULL
);

CREATE TABLE roles (
    id INTEGER AUTO_INCREMENT PRIMARY KEY, 
    title VARCHAR(30) NOT NULL,
    salary DE
    CONSTRAINT fk_party FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL
)

CREATE TABLE department (
    id INTEGER AUTO_INCREMENT PRIMARY KEY, 
    dept_name VARCHAR(30) NOT NULL
);